INSERT INTO movie (id, title, synopsis, genre, type, rating, duration, poster, trailerUrl) VALUES
(1, 'El Señor de los Anillos: La Comunidad del Anillo', 'Frodo, un hobbit pacífico, hereda un anillo que Sauron desea recuperar para dominar la Tierra Media. Junto a aliados como Gandalf y Aragorn, se embarca en una peligrosa misión para destruirlo en el Monte del Destino, enfrentando orcos y traiciones.', [1], 'Estreno', 'PG-13', 178, 'https://imgcartelera.s3.us-east-2.amazonaws.com/assets/lord_of_the_rings.jpg', 'kMD16QImEBI'),
(2, 'El Hobbit', 'Bilbo Bolsón es reclutado por Gandalf y un grupo de enanos para recuperar el reino enano de Erebor, controlado por el dragón Smaug. Durante su viaje, Bilbo descubre su propio valor y encuentra el Anillo Único, que cambiará el curso de la Tierra Media.', [1], 'Estreno', 'PG-13', 169, 'https://imgcartelera.s3.us-east-2.amazonaws.com/assets/el_hobbit.jpg', 'sI8OQRXhcZE'),
(3, 'Van Helsing', 'Gabriel Van Helsing, cazador de monstruos, lucha contra Drácula en Transilvania. Junto a Anna Valerious, enfrenta vampiros y criaturas sobrenaturales para detener los planes del conde, en una batalla contra fuerzas oscuras.', [3], 'Estreno', 'PG-13', 132, 'https://imgcartelera.s3.us-east-2.amazonaws.com/assets/van_helsing.jpg', '3fdRKme00uI'),
(4, 'Harry Potter y el Cáliz de Fuego', 'Harry es involuntariamente inscrito en el Torneo de los Tres Magos, donde enfrenta peligros y descubre un complot oscuro que incluye el regreso de Lord Voldemort, amenazando el mundo mágico.', [1], 'Estreno', 'PG-13', 157, 'https://imgcartelera.s3.us-east-2.amazonaws.com/assets/harry_potter.jpg', 'mNgwNXKBEW0'),
(5, 'La Monja', 'Después de un suicidio en un convento rumano, el sacerdote Burke y la novicia Irene investigan la conexión con la demoníaca Valak, enfrentándose a una aterradora batalla mientras desvelan oscuros secretos del pasado.', [5], 'Reestreno', 'R', 96, 'https://imgcartelera.s3.us-east-2.amazonaws.com/assets/la_monja.jpg', 'eqVjGwYFVqQ'),
(6, 'Annabelle', 'Tras un ataque demoníaco, John y Mia llamados a enfrentar a Annabelle, una muñeca poseída que genera terror en su hogar. Luchan por proteger a sus seres queridos de una fuerza maligna que los acecha.', [5], 'Estreno', 'R', 98, 'https://imgcartelera.s3.us-east-2.amazonaws.com/assets/annabelle.jpg', 'EMa-KFfatT0I'),
(7, 'Terrifier', 'En Halloween, un grupo de jóvenes se convierte en víctima de Art, un aterrador asesino enmascarado que tortura y mata sin piedad. La lucha por la supervivencia se vuelve una sangrienta pesadilla.', [5], 'Estreno', 'R', 82, 'https://imgcartelera.s3.us-east-2.amazonaws.com/assets/terrifier.jpg', 'fN5j1MtGO2Q'),
(8, 'John Wick', 'Tras la muerte de su esposa y el asesinato de su perro, John Wick, un exasesino, regresa al mundo del crimen para buscar venganza, desatando una oleada de caos y violencia.', [3], 'Reestreno', 'R', 101, 'https://imgcartelera.s3.us-east-2.amazonaws.com/assets/john_wick.jpg', 'C0BMx-qxsP4'),
(9, 'Volver al Futuro III', 'Marty McFly viaja a 1885 para rescatar a Doc Brown, atrapado en el pasado. Enfrentará bandidos y peligros nuevos mientras intenta regresar al futuro y reparar el tiempo alterado.', [7], 'Reestreno', 'PG', 118, 'https://imgcartelera.s3.us-east-2.amazonaws.com/assets/volver_al_futuro_3.jpg', 'WmBX7CA-AAc'),
(10, 'Shrek 2', 'Tras casarse con Fiona, Shrek visita a sus suegros, donde enfrenta su desaprobación. Junto a Donkey y el Gato con Botas, debe demostrar que el verdadero valor no está en la apariencia.', [8], 'Estreno', 'PG', 93, 'https://imgcartelera.s3.us-east-2.amazonaws.com/assets/shrek_2.jpg', 'Z1ELiRdwpg4'),
(11, 'Piratas del Caribe: La Maldición de la Perla Negra', 'El capitán Jack Sparrow busca recuperar su barco, la Perla Negra, mientras se enfrenta a la maldición de un tesoro que ha transformado a la tripulación de Barbosa en esqueletos.', [2], 'Reestreno', 'PG-13', 143, 'https://imgcartelera.s3.us-east-2.amazonaws.com/assets/piratas_del_caribe.jpg', 'azjsS0wxTA8'),
(12, 'Escuela de Rock', 'Dewey Finn, un músico fracasado, se disfraza de profesor y forma una banda de rock con sus estudiantes, inspirándolos a luchar por sus sueños y a descubrir su verdadero talento musical.', [4], 'Estreno', 'PG-13', 108, 'https://imgcartelera.s3.us-east-2.amazonaws.com/assets/school_of_rock.jpg', 'TExoc0MG4I4');

COMMIT;